import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
	render() {
		return (
			<Html lang="en">
				<Head>
					<meta httpEquiv="Content-type" content="text/html; charset=utf-8" />
					<meta name="robots" content="follow, index, noodp" />
					<meta
						name="viewport"
						content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
					/>
					<meta
						name="description"
						content="Help other people find great pizza to eat by voting for the best pizza restaurants near you. View local pizza restaurants in your area and vote for your favorite place to eat pizza."
					/>
					<meta name="description" content="Generated by create next app" />
					<meta httpEquiv="x-ua-compatible" content="IE=edg, chrome=1" />
					<meta
						name="keywords"
						content="pizza, picker, pizza picker, restaurant, pizza restaurant, favorite pizza restaurant, pick pizza, pick restaurant, pick pizza restaurant, pick favorite pizza restaurant, best pizza restaurants, best pizza places, top pizza restaurants"
					/>
					<meta property="og:url" content="https://pizzapicker.app/" />
					<meta property="og:title" content="Pizza Picker" />
					<meta property="og:site_name" content="Pizza Picker" />
					<meta property="og:type" content="website" />
					<meta property="og:locale" content="en_US" />
					<title>Pizza Picker</title>
					<link
						rel="apple-touch-icon"
						sizes="180x180"
						href="/static/apple-touch-icon.png"
					/>
					<link
						rel="icon"
						type="image/png"
						sizes="32x32"
						href="/static/favicon-32x32.png"
					/>
					<link
						rel="icon"
						type="image/png"
						sizes="16x16"
						href="/static/favicon-16x16.png"
					/>
					<link rel="manifest" href="/static/site.webmanifest" />
					<link rel="icon" href="/static/favicon.ico" />
				</Head>
				<body>
					<Main />
					<NextScript />
				</body>
			</Html>
		);
	}
}

export default MyDocument;
