import Head from 'next/head';
import Banner from '../components/Banner/Banner';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home = () => {
	const bannerBtnClickHandler = () => {
		console.log('BUTTON CLICKED');
	};

	return (
		<div className={styles.container}>
			<Head>
				{/* <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <meta http-equiv="x-ua-compatible" content="IE=edg, chrome=1" />
        <meta
          name="keywords"
          content="software engineer, software development, bill, bill masters, bilal masters, bilal, masters, portfolio, web design company, web development company, software development company, software, software development company"
        />
        <meta property="og:url" content="https://bilalmasters.com/" />
        <meta property="og:title" content="Bilal Masters" />
        <meta property="og:description" content="software engineer" /> */}
				<title>Pizza Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText="View restaurants nearby"
					handleOnClick={bannerBtnClickHandler}
				/>
				<div className={styles.heroImage}>
					<Image src="/static/pizza-hero-img.jpeg" width={800} height={550} />
				</div>
			</main>
		</div>
	);
};

export default Home;
