import Head from 'next/head';
import Banner from '../components/Banner/Banner';
import styles from '../styles/Home.module.css';

export default function Home() {
	const bannerBtnClickHandler = () => {
		console.log('BUTTON CLICKED');
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Pizza Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText="View restaurants nearby"
					handleOnClick={bannerBtnClickHandler}
				/>
			</main>
		</div>
	);
}
